name: Update Repository on Push

on:
  repository_dispatch:
  push:
    branches:
      - master
    paths:
      - '**/*'  # Detecta cambios en cualquier archivo

jobs:
  update-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "MunchiA"
          git config --global user.email "147060584+MunchiA@users.noreply.github.com"
          git config --global rerere.enabled true

      - name: Add Remote Upstream
        run: |
          git remote add upstream https://github.com/keldaanCommunity/pokemonAutoChess.git
          git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git checkout master
          git merge upstream/master --strategy-option ours --allow-unrelated-histories

      - name: Push to Origin
        run: |
          git push origin master
